### ISSUE TITLE
"Node 'ND' has no position" error 

### ISSUE THREAD

**Issue by cogrpar** [dwavesystems/dwave_networkx#152]
Hello,
I am using windows 10 and python 3.7.4 to run the map coloring example code in the d'wave ocean documentation: [https://docs.ocean.dwavesys.com/en/latest/examples/map_kerberos.html](url)

This is what my code looks like:

```
import networkx as nx

G = nx.read_adjlist('C:\\Users\\cogrpar\\AppData\\Local\\Programs\\Python\\Python37\\usa.adj', delimiter = ',')

import dwave_networkx as dnx
from hybrid.reference.kerberos import KerberosSampler

coloring = dnx.min_vertex_coloring(G, sampler=KerberosSampler(), chromatic_ub=4, max_iter=10, convergence=3)
print (set(coloring.values()))

import matplotlib.pyplot as plt
node_colors = [coloring.get(node) for node in G.nodes()]
if dnx.is_vertex_coloring(G, coloring):  # adjust the next line if using a different map
    nx.draw(G, pos=nx.shell_layout(G, nlist = [list(G.nodes)[x:x+10] for x in range(0, 50, 10)] + [[list(G.nodes)[50]]]), with_labels=True, node_color=node_colors, node_size=400, cmap=plt.cm.rainbow)
plt.show()


```
When I attempt to run this code, I get the following error:

```
Traceback (most recent call last):
  File "C:\Users\cogrpar\AppData\Local\Programs\Python\Python37\lib\site-packages\networkx\drawing\nx_pylab.py", line 397, in draw_networkx_nodes
    xy = np.asarray([pos[v] for v in nodelist])
  File "C:\Users\cogrpar\AppData\Local\Programs\Python\Python37\lib\site-packages\networkx\drawing\nx_pylab.py", line 397, in <listcomp>
    xy = np.asarray([pos[v] for v in nodelist])
KeyError: 'ND'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\cogrpar\AppData\Local\Programs\Python\Python37\mapColoringTest.py", line 14, in <module>
    nx.draw(G, pos=nx.shell_layout(G, nlist = [list(G.nodes)[x:x+10] for x in range(0, 50, 10)] + [[list(G.nodes)[50]]]), with_labels=True, node_color=node_colors, node_size=400, cmap=plt.cm.rainbow)
  File "C:\Users\cogrpar\AppData\Local\Programs\Python\Python37\lib\site-packages\networkx\drawing\nx_pylab.py", line 125, in draw
    draw_networkx(G, pos=pos, ax=ax, **kwds)
  File "C:\Users\cogrpar\AppData\Local\Programs\Python\Python37\lib\site-packages\networkx\drawing\nx_pylab.py", line 274, in draw_networkx
    node_collection = draw_networkx_nodes(G, pos, **kwds)
  File "C:\Users\cogrpar\AppData\Local\Programs\Python\Python37\lib\site-packages\networkx\drawing\nx_pylab.py", line 399, in draw_networkx_nodes
    raise nx.NetworkXError('Node %s has no position.' % e)
networkx.exception.NetworkXError: Node 'ND' has no position.
```

I would really appreciate any help in trying to resolve the issue
Thanks in advance for any help

**Comment by cogrpar** [comment]
Sorry this was an error with the networkx library not dwave-networkx, and the issue was due to me forgetting to get rid of the comments at the top of the usa.adj file.  Removing these comments fixed the issue.
